services:
  certcheckerbot:
    image: ghcr.io/stuchalin/certcheckerbot:main
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - certcheckerbotdata:/opt/certcheckbot/

volumes:
  certcheckerbotdata: